<a href="https://colab.research.google.com/github/steven-blanco/Proyecto-Netlflix/blob/main/Proyecto_Netflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Paso 1 . Carga de librerías y exploración de datos**

In [ ]:
#Importar librerias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#Cargar dataset
df = pd.read_csv("/content/drive/MyDrive/BI_Netflix_Exploded.csv")

In [ ]:
#Exploración del dataset
df.head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows
2,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Dramas
3,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Mysteries
4,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,Crime TV Shows
5,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,International TV Shows
6,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Action & Adventure
7,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,Docuseries
8,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,Reality TV
9,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows
10,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,Romantic TV Shows
11,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,TV Comedies
12,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Dramas
13,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Horror
14,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Mysteries
15,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies
16,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,Dramas
17,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,Independent Movies
18,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,International Movies
19,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,British TV Shows

Observamos dos cosas importantes en el dataset:
1.   Existen producciones repetidas en la lista cuyo única diferenciación es el dato registrado en la columna `listed_in`.
2.   Existen producciones que fueron colaboraciones entre distintos países. Se trabajará más adelante con ello.

In [ ]:
#Observación de conteo y formato en el df original
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19323 entries, 0 to 19322
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       19323 non-null  object
 1   type          19323 non-null  object
 2   title         19323 non-null  object
 3   director      13439 non-null  object
 4   cast          17819 non-null  object
 5   country       17601 non-null  object
 6   date_added    19303 non-null  object
 7   release_year  19323 non-null  int64
 8   rating        18742 non-null  object
 9   duration      19323 non-null  object
 10  listed_in     19323 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.6+ MB

In [ ]:
#Creación de los datasets
data_país = df.copy()
data_rating = df.copy()

In [ ]:
data_país.head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows
2,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Dramas
3,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Mysteries
4,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,Crime TV Shows
5,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,International TV Shows
6,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Action & Adventure
7,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,Docuseries
8,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,Reality TV
9,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows
10,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,Romantic TV Shows
11,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,TV Comedies
12,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Dramas
13,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Horror
14,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Mysteries
15,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies
16,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,Dramas
17,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,Independent Movies
18,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,International Movies
19,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,British TV Shows

In [ ]:
data_rating.head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows
2,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Dramas
3,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Mysteries
4,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,Crime TV Shows
5,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,International TV Shows
6,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Action & Adventure
7,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,Docuseries
8,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,Reality TV
9,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows
10,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,Romantic TV Shows
11,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,TV Comedies
12,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Dramas
13,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Horror
14,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,TV Mysteries
15,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies
16,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,Dramas
17,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,Independent Movies
18,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,International Movies
19,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,British TV Shows

In [ ]:
#Eliminamos las columnas no necesarias para los datasets
data_país.drop(['director', 'cast', 'duration', 'date_added','listed_in'], axis = 1, inplace = True, errors= 'ignore')
data_país.reset_index(drop=True, inplace=True)
data_rating.drop(['director', 'cast', 'duration', 'date_added','listed_in','country'], axis = 1, inplace = True, errors= 'ignore')
data_rating.reset_index(drop=True, inplace=True)

Elimino las columnas que no necesito en mis datasets nuevos.

In [ ]:
#Verifico cambios
data_país.head(20)

,show_id,type,title,country,release_year,rating
0,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13
1,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
2,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
3,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
4,s3,TV Show,Ganglands,NaN,2021,TV-MA
5,s3,TV Show,Ganglands,NaN,2021,TV-MA
6,s3,TV Show,Ganglands,NaN,2021,TV-MA
7,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA
8,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA
9,s5,TV Show,Kota Factory,India,2021,TV-MA
10,s5,TV Show,Kota Factory,India,2021,TV-MA
11,s5,TV Show,Kota Factory,India,2021,TV-MA
12,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
13,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
14,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
15,s7,Movie,My Little Pony: A New Generation,NaN,2021,PG
16,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA
17,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA
18,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA
19,s9,TV Show,The Great British Baking Show,United Kingdom,2021,TV-14

In [ ]:
data_rating.head(20)

   show_id     type                             title  release_year rating
0       s1    Movie              Dick Johnson Is Dead          2020  PG-13
1       s2  TV Show                     Blood & Water          2021  TV-MA
2       s2  TV Show                     Blood & Water          2021  TV-MA
3       s2  TV Show                     Blood & Water          2021  TV-MA
4       s3  TV Show                         Ganglands          2021  TV-MA
5       s3  TV Show                         Ganglands          2021  TV-MA
6       s3  TV Show                         Ganglands          2021  TV-MA
7       s4  TV Show             Jailbirds New Orleans          2021  TV-MA
8       s4  TV Show             Jailbirds New Orleans          2021  TV-MA
9       s5  TV Show                      Kota Factory          2021  TV-MA
10      s5  TV Show                      Kota Factory          2021  TV-MA
11      s5  TV Show                      Kota Factory          2021  TV-MA
12      s6  TV Show                     Midnight Mass          2021  TV-MA
13      s6  TV Show                     Midnight Mass          2021  TV-MA
14      s6  TV Show                     Midnight Mass          2021  TV-MA
15      s7    Movie  My Little Pony: A New Generation          2021     PG
16      s8    Movie                           Sankofa          1993  TV-MA
17      s8    Movie                           Sankofa          1993  TV-MA
18      s8    Movie                           Sankofa          1993  TV-MA
19      s9  TV Show     The Great British Baking Show          2021  TV-14

Notemos que con la eliminación de la columna `listed_in` en el data_rating, existen filas completamente duplicadas. Nos encargaremos más adelante.

In [ ]:
#Información de nuevos datasets
data_país.info()
data_rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19323 entries, 0 to 19322
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       19323 non-null  object
 1   type          19323 non-null  object
 2   title         19323 non-null  object
 3   country       17601 non-null  object
 4   release_year  19323 non-null  int64
 5   rating        18742 non-null  object
dtypes: int64(1), object(5)
memory usage: 905.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19323 entries, 0 to 19322
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       19323 non-null  object
 1   type          19323 non-null  object
 2   title         19323 non-null  object
 3   release_year  19323 non-null  int64
 4   rating        18742 non-null  object
dtypes: int64(1), object(4)
memory usage: 754.9+ KB

Los dataframes creados contienen inicialmente la misma cantidad de filas que el dataset original.

In [ ]:
#Separación de países
data_país['country'] = data_país['country'].str.split(', ')
data_país = data_país.explode('country')
data_país.head(20)

,show_id,type,title,country,release_year,rating
0,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13
1,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
2,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
3,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
4,s3,TV Show,Ganglands,NaN,2021,TV-MA
5,s3,TV Show,Ganglands,NaN,2021,TV-MA
6,s3,TV Show,Ganglands,NaN,2021,TV-MA
7,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA
8,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA
9,s5,TV Show,Kota Factory,India,2021,TV-MA
10,s5,TV Show,Kota Factory,India,2021,TV-MA
11,s5,TV Show,Kota Factory,India,2021,TV-MA
12,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
13,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
14,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
15,s7,Movie,My Little Pony: A New Generation,NaN,2021,PG
16,s8,Movie,Sankofa,United States,1993,TV-MA
16,s8,Movie,Sankofa,Ghana,1993,TV-MA
16,s8,Movie,Sankofa,Burkina Faso,1993,TV-MA
16,s8,Movie,Sankofa,United Kingdom,1993,TV-MA

In [ ]:
data_país.shape

(23754, 6)

El código para data_país logró separar en filas distintas las producciones en colaboración con distintos países para estandarizar el conteo. Notamos que:
1.   Existen filas con información completamente repetida al haber eliminado la columna `listed_in`
2.   Al separar en filas distintas las producciones con países en colaboración, se sumaron las entradas del dataset.

In [ ]:
#Verificamos duplicados
data_país.duplicated().sum()

np.int64(12909)

In [ ]:
data_rating.duplicated().sum()

np.int64(10516)

In [ ]:
#Eliminamos las filas completamente iguales
data_país = data_país.drop_duplicates(keep='first').reset_index(drop=True)
data_país.duplicated().sum()

np.int64(0)

In [ ]:
data_país.head(20)

,show_id,type,title,country,release_year,rating
0,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13
1,s2,TV Show,Blood & Water,South Africa,2021,TV-MA
2,s3,TV Show,Ganglands,NaN,2021,TV-MA
3,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA
4,s5,TV Show,Kota Factory,India,2021,TV-MA
5,s6,TV Show,Midnight Mass,NaN,2021,TV-MA
6,s7,Movie,My Little Pony: A New Generation,NaN,2021,PG
7,s8,Movie,Sankofa,United States,1993,TV-MA
8,s8,Movie,Sankofa,Ghana,1993,TV-MA
9,s8,Movie,Sankofa,Burkina Faso,1993,TV-MA
10,s8,Movie,Sankofa,United Kingdom,1993,TV-MA
11,s8,Movie,Sankofa,Germany,1993,TV-MA
12,s8,Movie,Sankofa,Ethiopia,1993,TV-MA
13,s9,TV Show,The Great British Baking Show,United Kingdom,2021,TV-14
14,s10,Movie,The Starling,United States,2021,PG-13
15,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,2021,TV-MA
16,s12,TV Show,Bangkok Breaking,NaN,2021,TV-MA
17,s13,Movie,Je Suis Karl,Germany,2021,TV-MA
18,s13,Movie,Je Suis Karl,Czech Republic,2021,TV-MA
19,s14,Movie,Confessions of an Invisible Girl,NaN,2021,TV-PG

In [ ]:
data_rating = data_rating.drop_duplicates(keep='first').reset_index(drop=True)
data_rating.duplicated().sum()

np.int64(0)

In [ ]:
print(data_país.shape)
print(data_rating.shape)

(10845, 6)
(8807, 5)

In [ ]:
#Observamos la proporción de los nulos en los datasets
data_país.info()
data_país.isna().sum()
data_país.isna().sum()/len(data_país)*100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10845 entries, 0 to 10844
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       10845 non-null  object
 1   type          10845 non-null  object
 2   title         10845 non-null  object
 3   country       10014 non-null  object
 4   release_year  10845 non-null  int64
 5   rating        10528 non-null  object
dtypes: int64(1), object(5)
memory usage: 508.5+ KB

show_id         0.000000
type            0.000000
title           0.000000
country         7.662517
release_year    0.000000
rating          2.923006
dtype: float64

In [ ]:
data_rating.info()
data_rating.isna().sum()
data_rating.isna().sum()/len(data_rating)*100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   release_year  8807 non-null   int64
 4   rating        8530 non-null   object
dtypes: int64(1), object(4)
memory usage: 344.2+ KB

show_id         0.000000
type            0.000000
title           0.000000
release_year    0.000000
rating          3.145225
dtype: float64

Las métricas de este proyecto se basarán en tres df distintos:
1. DF original para no perder información importante para las métricas de `type`y `listed_in`, independientemente de los valores de otras columnas.
2. data_país y data_rating para obtener métricas sin perder información por nulos en registros por columna clave en dichos df's.

In [ ]:
#Eliminamos las filas con valores nulos en las columnas seleccionadas en ambos sets.
data_rating.dropna(subset=['rating'], inplace=True)
data_rating.reset_index(drop=True, inplace=True)
data_país.dropna(subset=['country'], inplace=True)
data_país.reset_index(drop=True, inplace=True)

In [ ]:
#Comparación de cambios.
data_país.info()
data_país.isna().sum()
data_país.isna().sum()/len(data_país)*100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10014 entries, 0 to 10013
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       10014 non-null  object
 1   type          10014 non-null  object
 2   title         10014 non-null  object
 3   country       10014 non-null  object
 4   release_year  10014 non-null  int64
 5   rating        9708 non-null   object
dtypes: int64(1), object(5)
memory usage: 469.5+ KB

show_id         0.000000
type            0.000000
title           0.000000
country         0.000000
release_year    0.000000
rating          3.055722
dtype: float64

In [ ]:
data_rating.info()
data_rating.isna().sum()
data_rating.isna().sum()/len(data_rating)*100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8530 entries, 0 to 8529
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8530 non-null   object
 1   type          8530 non-null   object
 2   title         8530 non-null   object
 3   release_year  8530 non-null   int64
 4   rating        8530 non-null   object
dtypes: int64(1), object(4)
memory usage: 333.3+ KB

show_id         0.0
type            0.0
title           0.0
release_year    0.0
rating          0.0
dtype: float64

In [ ]:
#Guardamos datasets
data_rating.to_csv('df_listed.csv', index=False)
data_país.to_csv('df_país.csv', index=False)

**Paso 2: Métricas clave**

In [ ]:
#Cantidad de producciones en el catálogo de Netflix
print(df['show_id'].nunique())

8807

In [ ]:
#País con mayor cantidad de producciones
data_país.groupby('country')['show_id'].nunique().sort_values(ascending=False).head(1)

country
United States    3689
Name: show_id, dtype: int64

In [ ]:
#Porcentaje de implicación del país más popular en el catálogo
porcentaje = (
    data_país.groupby('country')['show_id'].nunique()
    / data_país['show_id'].nunique()
    * 100
)
porcentaje.sort_values(ascending=False).head(1)

country
United States    46.251254
Name: show_id, dtype: float64

In [ ]:
#Top 20 de países con menor cantidad de producciones
data_país.groupby('country')['show_id'].nunique().sort_values(ascending=True).head(20)

country
Afghanistan           1
Albania               1
Armenia               1
Angola                1
Belarus               1
Bermuda               1
Bahamas               1
Azerbaijan            1
Botswana              1
Cameroon              1
Cambodia,             1
Cuba                  1
Cyprus                1
Burkina Faso          1
East Germany          1
Dominican Republic    1
Jamaica               1
Liechtenstein         1
Lithuania             1
Kazakhstan            1
Name: show_id, dtype: int64

In [ ]:
#Cantidad de producciones que existen en el catálogo según tipo
df.groupby('type')['show_id'].nunique().sort_values(ascending=False).head()

type
Movie      6131
TV Show    2676
Name: show_id, dtype: int64

In [ ]:
#Mayor género de producciones por tipo de producción
conteo = (
    df.groupby(['type', 'listed_in'])['show_id']
      .nunique()
      .reset_index(name='producciones')
)

resultado = conteo.loc[
    conteo.groupby('type')['producciones'].idxmax()
]

print(resultado)

       type               listed_in  producciones
11    Movie    International Movies          2752
25  TV Show  International TV Shows          1351

In [ ]:
#Cantidad más popular de 'rating' clasificado por tipo de producción
resultado = (
    data_rating.groupby('type')['rating']
    .value_counts()
    .groupby(level=0)
    .head(1)
)
resultado

type     rating
Movie    TV-MA     1940
TV Show  TV-MA     1119
Name: count, dtype: int64